//
//  ShopCartMacroNotifications.m
//  仿购物车添加动画
//
//  Created by 王新伟 on 2017/6/24.
//  Copyright © 2017年 王新伟. All rights reserved.
//

#import "ShopCartMacroNotifications.h"

@implementation ShopCartMacroNotifications

@end

NSString * const ORDERLIST_CLICK_ADD_BUTTON_NOTIFICATION = @"ORDERLIST_CLICK_ADD_BUTTON_NOTIFICATION";

NSString * const ORDERLIST_CLICK_SUBTRACT_BUTTON_NOTIFICATION = @"ORDERLIST_CLICK_SUBTRACT_BUTTON_NOTIFICATION";

NSString * const SHOPCARTLIST_CLICK_ADD_BUTTON_NOTIFICATION = @"SHOPCARTLIST_CLICK_ADD_BUTTON_NOTIFICATION";

NSString * const SHOPCARTLIST_CLICK_SUBTRACT_BUTTON_NOTIFICATION = @"SHOPCARTLIST_CLICK_SUBTRACT_BUTTON_NOTIFICATION";
